//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataClasesQuickOrder.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEJAVULAOZ-PC\\MSSSQLSERVER2012;Initial Catalog=SistemaPedidos;Integra" +
            "ted Security=True")]
        public string SistemaPedidosConnectionString {
            get {
                return ((string)(this["SistemaPedidosConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANDRESOLARTE-PC\\SQLEXPRESS;Initial Catalog=QuickOrderDB;Integrated Se" +
            "curity=True")]
        public string QuickOrderDBConnectionString {
            get {
                return ((string)(this["QuickOrderDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANDRESOLARTE-PC\\SQLEXPRESS;Initial Catalog=SistemaPedidos;Integrated " +
            "Security=True")]
        public string SistemaPedidosConnectionString1 {
            get {
                return ((string)(this["SistemaPedidosConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\v11.0;Initial Catalog=SistemaPedidos;Integrated Security=Tr" +
            "ue")]
        public string SistemaPedidosConnectionString2 {
            get {
                return ((string)(this["SistemaPedidosConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=|DataDirectory|\\SistemaPedidos.mdf;I" +
            "ntegrated Security=True;Connect Timeout=30")]
        public string SistemaPedidosConnectionString3 {
            get {
                return ((string)(this["SistemaPedidosConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=\"C:\\Users\\AndresOlarte\\SkyDrive\\Repo" +
            "sitorio\\4 - Desarrollo\\1 - Codigo Fuente\\QuickOrder\\QuickOrder\\App_Data\\SistemaP" +
            "edidos.mdf\";Integrated Security=True")]
        public string SistemaPedidosConnectionString4 {
            get {
                return ((string)(this["SistemaPedidosConnectionString4"]));
            }
        }
    }
}
