<?xml version="1.0" encoding="utf-8"?><Database Name="SistemaPedidos" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ANDRESOLARTE-PC\SQLEXPRESS;Initial Catalog=SistemaPedidos;Integrated Security=True" SettingsObjectName="DataClasesQuickOrder.Properties.Settings" SettingsPropertyName="SistemaPedidosConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="dbo.ActualizarUsuario" Method="ActualizarUsuario">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Roles_idRoles" Parameter="roles_idRoles" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nom_Usuario" Parameter="nom_Usuario" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Contrasena" Parameter="contrasena" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Pregunta" Parameter="pregunta" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Respuesta_Pregunta" Parameter="respuesta_Pregunta" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Autentiacion" Method="Autentiacion">
    <Parameter Name="usuario" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="contrasena" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="AutentiacionResult">
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Roles_idRoles" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Primer_Nombre" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Segundo_Nombre" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Primer_Apellido" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Segundo_Apellido" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertRol" Method="InsertRol">
    <Parameter Name="Aplicacion" Parameter="aplicacion" Type="System.String" DbType="NVarChar(1)" />
    <Parameter Name="RolNombre" Parameter="rolNombre" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="NVarChar(256)" />
  </Function>
  <Function Name="dbo.LAOZ_InsertUsuario" Method="LAOZ_InsertUsuario">
    <Parameter Name="Roles_idRoles" Parameter="roles_idRoles" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nom_Usuario" Parameter="nom_Usuario" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Contrasena" Parameter="contrasena" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Pregunta" Parameter="pregunta" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Respuesta_Pregunta" Parameter="respuesta_Pregunta" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Elimina_producto" Method="sp_Elimina_producto">
    <Parameter Name="idProducto" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_eliminar_cliente_natural" Method="sp_eliminar_cliente_natural">
    <Parameter Name="Documento" Parameter="documento" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_eliminar_factura" Method="sp_eliminar_factura">
    <Parameter Name="idFactura" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_eliminar_producto" Method="sp_eliminar_producto">
    <Parameter Name="IdProducto" Parameter="idProducto" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_eliminar_producto_por_factura" Method="sp_eliminar_producto_por_factura">
    <Parameter Name="idFactura" Type="System.Int32" DbType="Int" />
    <Parameter Name="NomProducto" Parameter="nomProducto" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Cantidad" Parameter="cantidad" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_eliminar_vendedor" Method="sp_eliminar_vendedor">
    <Parameter Name="Documento" Parameter="documento" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_modificar_cliente_natural" Method="sp_modificar_cliente_natural">
    <Parameter Name="Documento" Parameter="documento" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Nuevo_Documento" Parameter="nuevo_Documento" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Nuevo_Tipo_Documento" Parameter="nuevo_Tipo_Documento" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="Nuevo_Primer_Nombre" Parameter="nuevo_Primer_Nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Nuevo_Segundo_Nombre" Parameter="nuevo_Segundo_Nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Nuevo_Primer_Apellido" Parameter="nuevo_Primer_Apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Nuevo_Segundo_Apellido" Parameter="nuevo_Segundo_Apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Nuevo_Telefono" Parameter="nuevo_Telefono" Type="System.String" DbType="VarChar(14)" />
    <Parameter Name="Nuevo_Direccion" Parameter="nuevo_Direccion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Nuevo_Pagina_Web" Parameter="nuevo_Pagina_Web" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Nuevo_Correo" Parameter="nuevo_Correo" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_modificar_producto" Method="sp_modificar_producto">
    <Parameter Name="IdProducto" Parameter="idProducto" Type="System.Int32" DbType="Int" />
    <Parameter Name="idCategoria" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nuevo_Nombre_Producto" Parameter="nuevo_Nombre_Producto" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Nuevo_Unidades_Disponibles" Parameter="nuevo_Unidades_Disponibles" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nuevo_Descripcion" Parameter="nuevo_Descripcion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Nuevo_Precio" Parameter="nuevo_Precio" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Nuevo_IVA" Parameter="nuevo_IVA" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_modificar_vendedor" Method="sp_modificar_vendedor">
    <Parameter Name="Documento" Parameter="documento" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Nuevo_Documento" Parameter="nuevo_Documento" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Nuevo_Tipo_Documento" Parameter="nuevo_Tipo_Documento" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="Nuevo_Primer_Nombre" Parameter="nuevo_Primer_Nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Nuevo_Segundo_Nombre" Parameter="nuevo_Segundo_Nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Nuevo_Primer_Apellido" Parameter="nuevo_Primer_Apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Nuevo_Segundo_Apellido" Parameter="nuevo_Segundo_Apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Nuevo_Telefono" Parameter="nuevo_Telefono" Type="System.String" DbType="VarChar(14)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_producto_por_factura" Method="sp_producto_por_factura">
    <Parameter Name="Nombre_Producto" Parameter="nombre_Producto" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="id_Factura" Type="System.Int32" DbType="Int" />
    <Parameter Name="Cantidad" Parameter="cantidad" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_registrar_administrador" Method="sp_registrar_administrador">
    <Parameter Name="Nom_Usuario" Parameter="nom_Usuario" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Contraseña" Parameter="contraseña" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Pregunta" Parameter="pregunta" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Respuesta_Pregunta" Parameter="respuesta_Pregunta" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Documento" Parameter="documento" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Tipo_Documento" Parameter="tipo_Documento" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="Primer_Nombre" Parameter="primer_Nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Segundo_Nombre" Parameter="segundo_Nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Primer_Apellido" Parameter="primer_Apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Segundo_Apellido" Parameter="segundo_Apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(14)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_registrar_cliente_natural" Method="sp_registrar_cliente_natural">
    <Parameter Name="Nom_Usuario" Parameter="nom_Usuario" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Contraseña" Parameter="contraseña" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Pregunta" Parameter="pregunta" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Respuesta_Pregunta" Parameter="respuesta_Pregunta" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Documento" Parameter="documento" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Tipo_Documento" Parameter="tipo_Documento" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="Primer_Nombre" Parameter="primer_Nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Segundo_Nombre" Parameter="segundo_Nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Primer_Apellido" Parameter="primer_Apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Segundo_Apellido" Parameter="segundo_Apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(14)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Pagina_Web" Parameter="pagina_Web" Type="System.String" DbType="VarChar(50)" />
  </Function>
  <Function Name="dbo.sp_registrar_factura" Method="sp_registrar_factura">
    <Parameter Name="Nom_Vendedor" Parameter="nom_Vendedor" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Nom_Empresa" Parameter="nom_Empresa" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Nom_Cliente_Natural" Parameter="nom_Cliente_Natural" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Nom_Cliente_Empresarial" Parameter="nom_Cliente_Empresarial" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Forma_Pago" Parameter="forma_Pago" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_registrar_producto" Method="sp_registrar_producto">
    <Parameter Name="idCategoria" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre_Producto" Parameter="nombre_Producto" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Unidades_Disponibles" Parameter="unidades_Disponibles" Type="System.Int32" DbType="Int" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Precio" Parameter="precio" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="IVA" Parameter="iVA" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_registrar_usuario" Method="sp_registrar_usuario">
    <Parameter Name="Nom_Usuario" Parameter="nom_Usuario" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Contraseña" Parameter="contraseña" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Pregunta" Parameter="pregunta" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Rol" Parameter="rol" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Respuesta_Pregunta" Parameter="respuesta_Pregunta" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_registrar_vendedor" Method="sp_registrar_vendedor">
    <Parameter Name="Nom_Usuario" Parameter="nom_Usuario" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Contraseña" Parameter="contraseña" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Pregunta" Parameter="pregunta" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Respuesta_Pregunta" Parameter="respuesta_Pregunta" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Documento" Parameter="documento" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Tipo_Documento" Parameter="tipo_Documento" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="Primer_Nombre" Parameter="primer_Nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Segundo_Nombre" Parameter="segundo_Nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Primer_Apellido" Parameter="primer_Apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Segundo_Apellido" Parameter="segundo_Apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(14)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_reporte_factura" Method="sp_reporte_factura">
    <Parameter Name="idFactura" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_reporte_facturaResult">
      <Column Name="NomCli" Type="System.String" DbType="VarChar(61)" CanBeNull="true" />
      <Column Name="NomVen" Type="System.String" DbType="VarChar(61)" CanBeNull="true" />
      <Column Name="idFactura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaFactura" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="idProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductoNom" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CantProducto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrecioProducto" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="IVAProducto" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SubTotalProducto" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TotalFactura" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="NomEmp" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_total_factura" Method="sp_total_factura">
    <Parameter Name="idFactura" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>