#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataClasesQuickOrder
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SistemaPedidos")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DatabaseDataContext() : 
				base(global::DataClasesQuickOrder.Properties.Settings.Default.SistemaPedidosConnectionString4, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ActualizarUsuario")]
		public int ActualizarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="BigInt")] System.Nullable<long> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Roles_idRoles", DbType="Int")] System.Nullable<int> roles_idRoles, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nom_Usuario", DbType="VarChar(30)")] string nom_Usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contrasena", DbType="VarChar(30)")] string contrasena, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pregunta", DbType="VarChar(30)")] string pregunta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Respuesta_Pregunta", DbType="VarChar(30)")] string respuesta_Pregunta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(50)")] string correo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, roles_idRoles, nom_Usuario, contrasena, pregunta, respuesta_Pregunta, correo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Autentiacion")]
		public ISingleResult<AutentiacionResult> Autentiacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string contrasena)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario, contrasena);
			return ((ISingleResult<AutentiacionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertRol", IsComposable=true)]
		public object InsertRol([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Aplicacion", DbType="NVarChar(1)")] string aplicacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RolNombre", DbType="NVarChar(256)")] string rolNombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="NVarChar(256)")] string descripcion)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aplicacion, rolNombre, descripcion).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LAOZ_InsertUsuario")]
		public int LAOZ_InsertUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Roles_idRoles", DbType="Int")] System.Nullable<int> roles_idRoles, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nom_Usuario", DbType="VarChar(30)")] string nom_Usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contrasena", DbType="VarChar(30)")] string contrasena, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pregunta", DbType="VarChar(30)")] string pregunta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Respuesta_Pregunta", DbType="VarChar(30)")] string respuesta_Pregunta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(50)")] string correo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), roles_idRoles, nom_Usuario, contrasena, pregunta, respuesta_Pregunta, correo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_eliminar_cliente_natural")]
		public int sp_eliminar_cliente_natural([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Documento", DbType="VarChar(50)")] string documento)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), documento);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_eliminar_factura")]
		public int sp_eliminar_factura([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idFactura)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idFactura);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_eliminar_producto")]
		public int sp_eliminar_producto([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProducto", DbType="Int")] System.Nullable<int> idProducto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_eliminar_producto_por_factura")]
		public int sp_eliminar_producto_por_factura([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idFactura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NomProducto", DbType="VarChar(50)")] string nomProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cantidad", DbType="Int")] System.Nullable<int> cantidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idFactura, nomProducto, cantidad);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_eliminar_vendedor")]
		public int sp_eliminar_vendedor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Documento", DbType="VarChar(50)")] string documento)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), documento);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_modificar_cliente_natural")]
		public int sp_modificar_cliente_natural([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Documento", DbType="VarChar(50)")] string documento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nuevo_Documento", DbType="VarChar(50)")] string nuevo_Documento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nuevo_Tipo_Documento", DbType="VarChar(4)")] string nuevo_Tipo_Documento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nuevo_Primer_Nombre", DbType="VarChar(50)")] string nuevo_Primer_Nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nuevo_Segundo_Nombre", DbType="VarChar(50)")] string nuevo_Segundo_Nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nuevo_Primer_Apellido", DbType="VarChar(50)")] string nuevo_Primer_Apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nuevo_Segundo_Apellido", DbType="VarChar(50)")] string nuevo_Segundo_Apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nuevo_Telefono", DbType="VarChar(14)")] string nuevo_Telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nuevo_Direccion", DbType="VarChar(50)")] string nuevo_Direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nuevo_Pagina_Web", DbType="VarChar(50)")] string nuevo_Pagina_Web, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nuevo_Correo", DbType="VarChar(50)")] string nuevo_Correo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), documento, nuevo_Documento, nuevo_Tipo_Documento, nuevo_Primer_Nombre, nuevo_Segundo_Nombre, nuevo_Primer_Apellido, nuevo_Segundo_Apellido, nuevo_Telefono, nuevo_Direccion, nuevo_Pagina_Web, nuevo_Correo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_modificar_producto")]
		public int sp_modificar_producto([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProducto", DbType="Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCategoria, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nuevo_Nombre_Producto", DbType="VarChar(50)")] string nuevo_Nombre_Producto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nuevo_Unidades_Disponibles", DbType="Int")] System.Nullable<int> nuevo_Unidades_Disponibles, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MinimoUnidades", DbType="Int")] System.Nullable<int> minimoUnidades, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nuevo_Descripcion", DbType="VarChar(50)")] string nuevo_Descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nuevo_Precio", DbType="Decimal(18,2)")] System.Nullable<decimal> nuevo_Precio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nuevo_IVA", DbType="Decimal(18,2)")] System.Nullable<decimal> nuevo_IVA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ImagenUrl", DbType="VarChar(50)")] string imagenUrl)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto, idCategoria, nuevo_Nombre_Producto, nuevo_Unidades_Disponibles, minimoUnidades, nuevo_Descripcion, nuevo_Precio, nuevo_IVA, imagenUrl);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_modificar_vendedor")]
		public int sp_modificar_vendedor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Documento", DbType="VarChar(50)")] string documento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nuevo_Documento", DbType="VarChar(50)")] string nuevo_Documento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nuevo_Tipo_Documento", DbType="VarChar(4)")] string nuevo_Tipo_Documento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nuevo_Primer_Nombre", DbType="VarChar(50)")] string nuevo_Primer_Nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nuevo_Segundo_Nombre", DbType="VarChar(50)")] string nuevo_Segundo_Nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nuevo_Primer_Apellido", DbType="VarChar(50)")] string nuevo_Primer_Apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nuevo_Segundo_Apellido", DbType="VarChar(50)")] string nuevo_Segundo_Apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nuevo_Telefono", DbType="VarChar(14)")] string nuevo_Telefono)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), documento, nuevo_Documento, nuevo_Tipo_Documento, nuevo_Primer_Nombre, nuevo_Segundo_Nombre, nuevo_Primer_Apellido, nuevo_Segundo_Apellido, nuevo_Telefono);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_producto_por_factura")]
		public int sp_producto_por_factura([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre_Producto", DbType="VarChar(50)")] string nombre_Producto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_Factura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cantidad", DbType="Int")] System.Nullable<int> cantidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre_Producto, id_Factura, cantidad);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_registrar_administrador")]
		public int sp_registrar_administrador([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nom_Usuario", DbType="VarChar(50)")] string nom_Usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contraseña", DbType="VarChar(50)")] string contraseña, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pregunta", DbType="VarChar(50)")] string pregunta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Respuesta_Pregunta", DbType="VarChar(50)")] string respuesta_Pregunta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(50)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Documento", DbType="VarChar(50)")] string documento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo_Documento", DbType="VarChar(4)")] string tipo_Documento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Primer_Nombre", DbType="VarChar(50)")] string primer_Nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Segundo_Nombre", DbType="VarChar(50)")] string segundo_Nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Primer_Apellido", DbType="VarChar(50)")] string primer_Apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Segundo_Apellido", DbType="VarChar(50)")] string segundo_Apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(14)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(50)")] string direccion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nom_Usuario, contraseña, pregunta, respuesta_Pregunta, correo, documento, tipo_Documento, primer_Nombre, segundo_Nombre, primer_Apellido, segundo_Apellido, telefono, direccion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_registrar_cliente_natural", IsComposable=true)]
		public object sp_registrar_cliente_natural([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nom_Usuario", DbType="VarChar(50)")] string nom_Usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contraseña", DbType="VarChar(50)")] string contraseña, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pregunta", DbType="VarChar(50)")] string pregunta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Respuesta_Pregunta", DbType="VarChar(50)")] string respuesta_Pregunta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(50)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Documento", DbType="VarChar(50)")] string documento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo_Documento", DbType="VarChar(4)")] string tipo_Documento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Primer_Nombre", DbType="VarChar(50)")] string primer_Nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Segundo_Nombre", DbType="VarChar(50)")] string segundo_Nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Primer_Apellido", DbType="VarChar(50)")] string primer_Apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Segundo_Apellido", DbType="VarChar(50)")] string segundo_Apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(14)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(50)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pagina_Web", DbType="VarChar(50)")] string pagina_Web)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nom_Usuario, contraseña, pregunta, respuesta_Pregunta, correo, documento, tipo_Documento, primer_Nombre, segundo_Nombre, primer_Apellido, segundo_Apellido, telefono, direccion, pagina_Web).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_registrar_factura", IsComposable=true)]
		public object sp_registrar_factura([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nom_Vendedor", DbType="VarChar(50)")] string nom_Vendedor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nom_Empresa", DbType="VarChar(50)")] string nom_Empresa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nom_Cliente_Natural", DbType="VarChar(50)")] string nom_Cliente_Natural, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nom_Cliente_Empresarial", DbType="VarChar(50)")] string nom_Cliente_Empresarial, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Forma_Pago", DbType="VarChar(50)")] string forma_Pago)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nom_Vendedor, nom_Empresa, nom_Cliente_Natural, nom_Cliente_Empresarial, forma_Pago).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_registrar_producto")]
		public int sp_registrar_producto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCategoria, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre_Producto", DbType="VarChar(50)")] string nombre_Producto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Unidades_Disponibles", DbType="Int")] System.Nullable<int> unidades_Disponibles, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MinimoUnidades", DbType="Int")] System.Nullable<int> minimoUnidades, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(50)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Precio", DbType="Decimal(18,2)")] System.Nullable<decimal> precio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IVA", DbType="Decimal(18,2)")] System.Nullable<decimal> iVA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UrlImagen", DbType="VarChar(50)")] string urlImagen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCategoria, nombre_Producto, unidades_Disponibles, minimoUnidades, descripcion, precio, iVA, urlImagen);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_registrar_vendedor")]
		public int sp_registrar_vendedor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nom_Usuario", DbType="VarChar(50)")] string nom_Usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contraseña", DbType="VarChar(50)")] string contraseña, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pregunta", DbType="VarChar(50)")] string pregunta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Respuesta_Pregunta", DbType="VarChar(50)")] string respuesta_Pregunta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(50)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Documento", DbType="VarChar(50)")] string documento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo_Documento", DbType="VarChar(4)")] string tipo_Documento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Primer_Nombre", DbType="VarChar(50)")] string primer_Nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Segundo_Nombre", DbType="VarChar(50)")] string segundo_Nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Primer_Apellido", DbType="VarChar(50)")] string primer_Apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Segundo_Apellido", DbType="VarChar(50)")] string segundo_Apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(14)")] string telefono)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nom_Usuario, contraseña, pregunta, respuesta_Pregunta, correo, documento, tipo_Documento, primer_Nombre, segundo_Nombre, primer_Apellido, segundo_Apellido, telefono);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_reporte_factura")]
		public ISingleResult<sp_reporte_facturaResult> sp_reporte_factura([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idFactura)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idFactura);
			return ((ISingleResult<sp_reporte_facturaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_total_factura")]
		public int sp_total_factura([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idFactura)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idFactura);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_registrar_usuario")]
		public int sp_registrar_usuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nom_Usuario", DbType="VarChar(50)")] string nom_Usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contraseña", DbType="VarChar(50)")] string contraseña, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pregunta", DbType="VarChar(50)")] string pregunta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idRol, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Respuesta_Pregunta", DbType="VarChar(50)")] string respuesta_Pregunta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(50)")] string correo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nom_Usuario, contraseña, pregunta, idRol, respuesta_Pregunta, correo);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class AutentiacionResult
	{
		
		private int _idUsuario;
		
		private int _Roles_idRoles;
		
		private string _Primer_Nombre;
		
		private string _Segundo_Nombre;
		
		private string _Primer_Apellido;
		
		private string _Segundo_Apellido;
		
		private string _Direccion;
		
		private string _Telefono;
		
		private string _Correo;
		
		public AutentiacionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL")]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this._idUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Roles_idRoles", DbType="Int NOT NULL")]
		public int Roles_idRoles
		{
			get
			{
				return this._Roles_idRoles;
			}
			set
			{
				if ((this._Roles_idRoles != value))
				{
					this._Roles_idRoles = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primer_Nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Primer_Nombre
		{
			get
			{
				return this._Primer_Nombre;
			}
			set
			{
				if ((this._Primer_Nombre != value))
				{
					this._Primer_Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segundo_Nombre", DbType="VarChar(30)")]
		public string Segundo_Nombre
		{
			get
			{
				return this._Segundo_Nombre;
			}
			set
			{
				if ((this._Segundo_Nombre != value))
				{
					this._Segundo_Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primer_Apellido", DbType="VarChar(30)")]
		public string Primer_Apellido
		{
			get
			{
				return this._Primer_Apellido;
			}
			set
			{
				if ((this._Primer_Apellido != value))
				{
					this._Primer_Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segundo_Apellido", DbType="VarChar(30)")]
		public string Segundo_Apellido
		{
			get
			{
				return this._Segundo_Apellido;
			}
			set
			{
				if ((this._Segundo_Apellido != value))
				{
					this._Segundo_Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(14)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(100)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this._Correo = value;
				}
			}
		}
	}
	
	public partial class sp_reporte_facturaResult
	{
		
		private string _NomCli;
		
		private string _NomVen;
		
		private int _idFactura;
		
		private System.Nullable<System.DateTime> _FechaFactura;
		
		private int _idProducto;
		
		private string _ProductoNom;
		
		private System.Nullable<int> _CantProducto;
		
		private System.Nullable<decimal> _PrecioProducto;
		
		private System.Nullable<decimal> _IVAProducto;
		
		private System.Nullable<decimal> _SubTotalProducto;
		
		private System.Nullable<decimal> _TotalFactura;
		
		private string _NomEmp;
		
		public sp_reporte_facturaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomCli", DbType="VarChar(61)")]
		public string NomCli
		{
			get
			{
				return this._NomCli;
			}
			set
			{
				if ((this._NomCli != value))
				{
					this._NomCli = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomVen", DbType="VarChar(61)")]
		public string NomVen
		{
			get
			{
				return this._NomVen;
			}
			set
			{
				if ((this._NomVen != value))
				{
					this._NomVen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idFactura", DbType="Int NOT NULL")]
		public int idFactura
		{
			get
			{
				return this._idFactura;
			}
			set
			{
				if ((this._idFactura != value))
				{
					this._idFactura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaFactura", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaFactura
		{
			get
			{
				return this._FechaFactura;
			}
			set
			{
				if ((this._FechaFactura != value))
				{
					this._FechaFactura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProducto", DbType="Int NOT NULL")]
		public int idProducto
		{
			get
			{
				return this._idProducto;
			}
			set
			{
				if ((this._idProducto != value))
				{
					this._idProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductoNom", DbType="VarChar(30)")]
		public string ProductoNom
		{
			get
			{
				return this._ProductoNom;
			}
			set
			{
				if ((this._ProductoNom != value))
				{
					this._ProductoNom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantProducto", DbType="Int")]
		public System.Nullable<int> CantProducto
		{
			get
			{
				return this._CantProducto;
			}
			set
			{
				if ((this._CantProducto != value))
				{
					this._CantProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioProducto", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> PrecioProducto
		{
			get
			{
				return this._PrecioProducto;
			}
			set
			{
				if ((this._PrecioProducto != value))
				{
					this._PrecioProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IVAProducto", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> IVAProducto
		{
			get
			{
				return this._IVAProducto;
			}
			set
			{
				if ((this._IVAProducto != value))
				{
					this._IVAProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubTotalProducto", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> SubTotalProducto
		{
			get
			{
				return this._SubTotalProducto;
			}
			set
			{
				if ((this._SubTotalProducto != value))
				{
					this._SubTotalProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalFactura", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TotalFactura
		{
			get
			{
				return this._TotalFactura;
			}
			set
			{
				if ((this._TotalFactura != value))
				{
					this._TotalFactura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomEmp", DbType="VarChar(30)")]
		public string NomEmp
		{
			get
			{
				return this._NomEmp;
			}
			set
			{
				if ((this._NomEmp != value))
				{
					this._NomEmp = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
