<?xml version="1.0" encoding="utf-8"?><Database Name="QuickOrderDB" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ANDRESOLARTE-PC\SQLEXPRESS;Initial Catalog=QuickOrderDB;Integrated Security=True" SettingsObjectName="DataClasesQuickOrder.Properties.Settings" SettingsPropertyName="QuickOrderDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Administrador" Member="Administradors">
    <Type Name="Administrador">
      <Column Name="idAdministrador" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Usuario_idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tipo_Documento_idTipo_Documento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Documento" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Primer_Nombre" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Segundo_Nombre" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Primer_Apellido" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Segundo_Apellido" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Tipo_Documento_Administrador" Member="Tipo_Documento" ThisKey="Tipo_Documento_idTipo_Documento" OtherKey="idTipo_Documento" Type="Tipo_Documento" IsForeignKey="true" />
      <Association Name="Usuario_Administrador" Member="Usuario" ThisKey="Usuario_idUsuario" OtherKey="idUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Categoria" Member="Categorias">
    <Type Name="Categoria">
      <Column Name="idCategoria" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Categoria" Member="Categoria1" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Categoria_Producto" Member="Productos" ThisKey="idCategoria" OtherKey="CateGOria_idCateGOria" Type="Producto" />
    </Type>
  </Table>
  <Table Name="dbo.Cliente_Natural" Member="Cliente_Naturals">
    <Type Name="Cliente_Natural">
      <Column Name="idCliente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Usuario_idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tipo_Documento_idTipo_Documento" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Documento" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Primer_Nombre" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Segundo_Nombre" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Primer_Apellido" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Segundo_Apellido" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pagina_Web" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Cliente_Natural_Factura" Member="Facturas" ThisKey="idCliente" OtherKey="Cliente_Natural_idCliente_Natural" Type="Factura" />
      <Association Name="Tipo_Documento_Cliente_Natural" Member="Tipo_Documento" ThisKey="Tipo_Documento_idTipo_Documento" OtherKey="idTipo_Documento" Type="Tipo_Documento" IsForeignKey="true" />
      <Association Name="Usuario_Cliente_Natural" Member="Usuario" ThisKey="Usuario_idUsuario" OtherKey="idUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Factura" Member="Facturas">
    <Type Name="Factura">
      <Column Name="idFactura" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Vendedor_idVendedor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Empresa_idEmpresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cliente_Natural_idCliente_Natural" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cliente_Empresarial_idCliente_Empresarial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Forma_Pago_idForma_Pago" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_Factura" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="Factura_Producto_por_Factura" Member="Producto_por_Facturas" ThisKey="idFactura" OtherKey="Factura_idFactura" Type="Producto_por_Factura" />
      <Association Name="Cliente_Natural_Factura" Member="Cliente_Natural" ThisKey="Cliente_Natural_idCliente_Natural" OtherKey="idCliente" Type="Cliente_Natural" IsForeignKey="true" />
      <Association Name="Forma_Pago_Factura" Member="Forma_Pago" ThisKey="Forma_Pago_idForma_Pago" OtherKey="idForma_Pago" Type="Forma_Pago" IsForeignKey="true" />
      <Association Name="Vendedor_Factura" Member="Vendedor" ThisKey="Vendedor_idVendedor" OtherKey="idVendedor" Type="Vendedor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Forma_Pago" Member="Forma_Pagos">
    <Type Name="Forma_Pago">
      <Column Name="idForma_Pago" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Forma_Pago" Member="Forma_Pago1" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="Forma_Pago_Factura" Member="Facturas" ThisKey="idForma_Pago" OtherKey="Forma_Pago_idForma_Pago" Type="Factura" />
    </Type>
  </Table>
  <Table Name="dbo.Producto" Member="Productos">
    <Type Name="Producto">
      <Column Name="idProducto" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CateGOria_idCateGOria" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Unidades_disponibles" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nombre_Producto" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="IVA" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="Producto_Producto_por_Factura" Member="Producto_por_Facturas" ThisKey="idProducto" OtherKey="Producto_idProducto" Type="Producto_por_Factura" />
      <Association Name="Producto_Producto_por_Producto" Member="Producto_por_Productos" ThisKey="idProducto" OtherKey="Id_Hijo" Type="Producto_por_Producto" />
      <Association Name="Categoria_Producto" Member="Categoria" ThisKey="CateGOria_idCateGOria" OtherKey="idCategoria" Type="Categoria" IsForeignKey="true" />
      <Association Name="Producto_por_Producto_Producto" Member="Producto_por_Producto" ThisKey="idProducto" OtherKey="Id_Padre" Type="Producto_por_Producto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Producto_por_Factura" Member="Producto_por_Facturas">
    <Type Name="Producto_por_Factura">
      <Column Name="idProducto_por_Factura" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Producto_idProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Factura_idFactura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad_Producto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sub_Total" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="Factura_Producto_por_Factura" Member="Factura" ThisKey="Factura_idFactura" OtherKey="idFactura" Type="Factura" IsForeignKey="true" />
      <Association Name="Producto_Producto_por_Factura" Member="Producto" ThisKey="Producto_idProducto" OtherKey="idProducto" Type="Producto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Producto_por_Producto" Member="Producto_por_Productos">
    <Type Name="Producto_por_Producto">
      <Column Name="Id_Padre" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Id_Hijo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Producto_por_Producto_Producto" Member="Producto" ThisKey="Id_Padre" OtherKey="idProducto" Type="Producto" Cardinality="One" />
      <Association Name="Producto_Producto_por_Producto" Member="Producto1" ThisKey="Id_Hijo" OtherKey="idProducto" Type="Producto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role">
      <Column Name="idRoles" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Rol" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="Role_Usuario" Member="Usuarios" ThisKey="idRoles" OtherKey="Roles_idRoles" Type="Usuario" />
    </Type>
  </Table>
  <Table Name="dbo.Tipo_Documento" Member="Tipo_Documentos">
    <Type Name="Tipo_Documento">
      <Column Name="idTipo_Documento" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tipo_Documento" Member="Tipo_Documento1" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="Tipo_Documento_Administrador" Member="Administradors" ThisKey="idTipo_Documento" OtherKey="Tipo_Documento_idTipo_Documento" Type="Administrador" />
      <Association Name="Tipo_Documento_Cliente_Natural" Member="Cliente_Naturals" ThisKey="idTipo_Documento" OtherKey="Tipo_Documento_idTipo_Documento" Type="Cliente_Natural" />
      <Association Name="Tipo_Documento_Vendedor" Member="Vendedors" ThisKey="idTipo_Documento" OtherKey="Tipo_Documento_idTipo_Documento" Type="Vendedor" />
    </Type>
  </Table>
  <Table Name="dbo.Usuario" Member="Usuarios">
    <Type Name="Usuario">
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Roles_idRoles" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nom_Usuario" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Contraseña" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Pregunta" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Respuesta_Pregunta" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Usuario_Administrador" Member="Administradors" ThisKey="idUsuario" OtherKey="Usuario_idUsuario" Type="Administrador" />
      <Association Name="Usuario_Cliente_Natural" Member="Cliente_Naturals" ThisKey="idUsuario" OtherKey="Usuario_idUsuario" Type="Cliente_Natural" />
      <Association Name="Usuario_Vendedor" Member="Vendedors" ThisKey="idUsuario" OtherKey="Usuario_idUsuario" Type="Vendedor" />
      <Association Name="Role_Usuario" Member="Role" ThisKey="Roles_idRoles" OtherKey="idRoles" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Vendedor" Member="Vendedors">
    <Type Name="Vendedor">
      <Column Name="idVendedor" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Usuario_idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tipo_Documento_idTipo_Documento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Documento" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Primer_Nombre" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Segundo_Nombre" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Primer_Apellido" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Segundo_Apellido" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Association Name="Vendedor_Factura" Member="Facturas" ThisKey="idVendedor" OtherKey="Vendedor_idVendedor" Type="Factura" />
      <Association Name="Tipo_Documento_Vendedor" Member="Tipo_Documento" ThisKey="Tipo_Documento_idTipo_Documento" OtherKey="idTipo_Documento" Type="Tipo_Documento" IsForeignKey="true" />
      <Association Name="Usuario_Vendedor" Member="Usuario" ThisKey="Usuario_idUsuario" OtherKey="idUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.Autentiacion" Method="Autentiacion">
    <Parameter Name="usuario" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="contrasena" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="AutentiacionResult">
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Roles_idRoles" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Primer_Nombre" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Segundo_Nombre" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Primer_Apellido" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Segundo_Apellido" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertUsuario" Method="InsertUsuario">
    <Parameter Name="Roles_idRoles" Parameter="roles_idRoles" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nom_Usuario" Parameter="nom_Usuario" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Contrasena" Parameter="contrasena" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Pregunta" Parameter="pregunta" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Respuesta_Pregunta" Parameter="respuesta_Pregunta" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>