#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataClasesQuickOrder
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SistemaPedidos")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DatabaseDataContext() : 
				base(global::DataClasesQuickOrder.Properties.Settings.Default.SistemaPedidosConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LAOZ_InsertUsuario")]
		public int LAOZ_InsertUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Roles_idRoles", DbType="Int")] System.Nullable<int> roles_idRoles, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nom_Usuario", DbType="VarChar(30)")] string nom_Usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contrasena", DbType="VarChar(30)")] string contrasena, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pregunta", DbType="VarChar(30)")] string pregunta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Respuesta_Pregunta", DbType="VarChar(30)")] string respuesta_Pregunta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(50)")] string correo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), roles_idRoles, nom_Usuario, contrasena, pregunta, respuesta_Pregunta, correo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_registrar_cliente_natural")]
		public int sp_registrar_cliente_natural([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nom_Usuario", DbType="VarChar(50)")] string nom_Usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contraseña", DbType="VarChar(50)")] string contraseña, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pregunta", DbType="VarChar(50)")] string pregunta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Respuesta_Pregunta", DbType="VarChar(50)")] string respuesta_Pregunta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(50)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Documento", DbType="VarChar(50)")] string documento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo_Documento", DbType="VarChar(4)")] string tipo_Documento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Primer_Nombre", DbType="VarChar(50)")] string primer_Nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Segundo_Nombre", DbType="VarChar(50)")] string segundo_Nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Primer_Apellido", DbType="VarChar(50)")] string primer_Apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Segundo_Apellido", DbType="VarChar(50)")] string segundo_Apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(14)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(50)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pagina_Web", DbType="VarChar(50)")] string pagina_Web)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nom_Usuario, contraseña, pregunta, respuesta_Pregunta, correo, documento, tipo_Documento, primer_Nombre, segundo_Nombre, primer_Apellido, segundo_Apellido, telefono, direccion, pagina_Web);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Autentiacion")]
		public ISingleResult<AutentiacionResult> Autentiacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string contrasena)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario, contrasena);
			return ((ISingleResult<AutentiacionResult>)(result.ReturnValue));
		}
	}
	
	public partial class AutentiacionResult
	{
		
		private int _idUsuario;
		
		private int _Roles_idRoles;
		
		private string _Primer_Nombre;
		
		private string _Segundo_Nombre;
		
		private string _Primer_Apellido;
		
		private string _Segundo_Apellido;
		
		private string _Direccion;
		
		private string _Telefono;
		
		private string _Correo;
		
		public AutentiacionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL")]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this._idUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Roles_idRoles", DbType="Int NOT NULL")]
		public int Roles_idRoles
		{
			get
			{
				return this._Roles_idRoles;
			}
			set
			{
				if ((this._Roles_idRoles != value))
				{
					this._Roles_idRoles = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primer_Nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Primer_Nombre
		{
			get
			{
				return this._Primer_Nombre;
			}
			set
			{
				if ((this._Primer_Nombre != value))
				{
					this._Primer_Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segundo_Nombre", DbType="VarChar(30)")]
		public string Segundo_Nombre
		{
			get
			{
				return this._Segundo_Nombre;
			}
			set
			{
				if ((this._Segundo_Nombre != value))
				{
					this._Segundo_Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primer_Apellido", DbType="VarChar(30)")]
		public string Primer_Apellido
		{
			get
			{
				return this._Primer_Apellido;
			}
			set
			{
				if ((this._Primer_Apellido != value))
				{
					this._Primer_Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segundo_Apellido", DbType="VarChar(30)")]
		public string Segundo_Apellido
		{
			get
			{
				return this._Segundo_Apellido;
			}
			set
			{
				if ((this._Segundo_Apellido != value))
				{
					this._Segundo_Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(14)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(100)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this._Correo = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
